version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoring_olt
      MYSQL_USER: oltuser
      MYSQL_PASSWORD: oltpass
    networks:
      - app-network

  express-app:
    restart: on-failure
    build: 
      context: . # Ganti dengan path ke direktori aplikasi Express.js Anda
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://oltuser:oltpass@mysql:3306/monitoring_olt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
